#! /bin/bash

#############
# Autostart #
#############

# Launch sxhkd if executable
# pgrep -x sxhkd > /dev/null || sxhkd &

. $HOME/.xinitrc


################################
#### Enable Chinese numbers ####
################################
# bspc monitor -d Ò» ¶þ Èý ËÄ Îå Áù Æß °Ë ¾Å

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         3
bspc config window_gap           5
bspc config top_padding         17

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#
# Remove all reules first
# bspc rule -r *:*
# 1 > terminal
# # bspc rule -a gnome-terminal desktop='^1' 
# 2 > web
# bspc rule -a firefox desktop='^2'

